#!/bin/bash
[ $# -gt 0 ] || echo "Usage : $0 filename"
while [ $# -gt 0 ]
do
        for i in "$1"
        do
                mv "$1" "$(echo $1 |perl -MURI::Escape -ne 'print uri_unescape($_)')"
        done
        shift
done